spring:
  config:
    activate:
      on-profile: 'prod'

build:
  version: '1.0'

cards:
  message: 'Welcome to EazyBank cards related PROD APIs'
  contactDetails:
    name: 'Suleware'
    email: 'suleware@gmail.com'
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
